<a href="https://colab.research.google.com/github/Vaycold/pytorch_tutorial/blob/main/%2301.%ED%85%90%EC%84%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensor

    : 텐서는 배열이나 행렬과 매우 유사한 특수한 자료구조
    

In [1]:
import torch
import numpy as np

In [2]:
# 데이터로부터 직접 생성
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
# Numpy 배열로부터 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_np

tensor([[1, 2],
        [3, 4]])

In [6]:
# 다른 텐서로부터 생성
'''
명시적으로 재정의하지 않으면 인자로 주어진 텐서의 속상, 자료형을 유지함
'''
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [7]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.4900, 0.5729],
        [0.9032, 0.4790]])

In [8]:
# 무작위 또는 상수 값을 사용하기
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.3844, 0.6017, 0.2054],
        [0.9826, 0.7143, 0.0113]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
# 텐서의 속성
'''
텐서의 속성은 텐서의 모양, 자료형, 어느장치에 저장되는 지를 나타냄
'''
tensor = torch.rand(3,4)
print('Shape of tensor : ', tensor.shape)
print('Datatype of tensor : ', tensor.dtype)
print('Device tensor is sored on : ', tensor.device)

Shape of tensor :  torch.Size([3, 4])
Datatype of tensor :  torch.float32
Device tensor is sored on :  cpu


In [12]:
# 텐서 연산
tensor = torch.ones(4,4)
print('1st row : ', tensor[0])
print('1st column : ', tensor[:,0])
print('Last column : ', tensor[...,-1])

tensor[:,1] = 0
print(tensor)

1st row :  tensor([1., 1., 1., 1.])
1st column :  tensor([1., 1., 1., 1.])
Last column :  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [21]:
# 텐서 합치기

t1 = torch.cat([tensor, tensor])
print(t1)
print(t1.shape)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
torch.Size([8, 4])


In [22]:
t2 = torch.cat([tensor, tensor], axis=1)
print(t2)
print(t2.shape)

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])
torch.Size([4, 8])


In [23]:
print(torch.stack((tensor,tensor)))
print(torch.stack((tensor,tensor)).shape)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])
torch.Size([2, 4, 4])


In [25]:
print(torch.stack((tensor,tensor),axis=1))
print(torch.stack((tensor,tensor),axis=1).shape)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.]]])
torch.Size([4, 2, 4])


In [51]:
test1 = torch.randint(10,(3,3))
test2 = torch.randint(10,(3,2))

print(test1,'\n')
print(test2)

tensor([[6, 1, 8],
        [6, 8, 6],
        [3, 6, 2]]) 

tensor([[2, 4],
        [3, 7],
        [4, 5]])


In [52]:
print(torch.cat([test1,test1]))
print('')
print(torch.cat([test1,test1],axis=1))

tensor([[6, 1, 8],
        [6, 8, 6],
        [3, 6, 2],
        [6, 1, 8],
        [6, 8, 6],
        [3, 6, 2]])

tensor([[6, 1, 8, 6, 1, 8],
        [6, 8, 6, 6, 8, 6],
        [3, 6, 2, 3, 6, 2]])


In [53]:
print(torch.cat([test1,test2]))
print('')
#print(torch.cat([test,test],axis=1))

RuntimeError: ignored

In [54]:
print('')
print(torch.cat([test1,test2],axis=1))


tensor([[6, 1, 8, 2, 4],
        [6, 8, 6, 3, 7],
        [3, 6, 2, 4, 5]])


In [56]:
torch.stack((test1,test2))

RuntimeError: ignored

In [72]:
torch.stack((test1,test2),axis=2)

RuntimeError: ignored

In [96]:
# 산술연산
'''
행렬 곱 /// y1==y2==y3
'''
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor) # tensor와 똑같은 사이즈의 random으로 생성
torch.matmul(tensor, tensor.T, out=y3)

print(y3)
'''
요소별 곱  // z1==z2==z3
'''
z1 = tensor*tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [98]:
# 요소가 1개인 텐서의 경우 item()을 사용하여 python 숫자 값으로 변환 가능
agg = tensor.sum()
agg

tensor(12.)

In [99]:
print(agg.item())

12.0


In [100]:
# 바꿔치기 연산
# 연산결과를 피연산자에 저장하는 연산을 바꿔치기 연산
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [101]:
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [102]:
# 넘파이 변환
t = torch.ones(5)
print(t)

n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [103]:
# 텐서의 변경 사항이 넘파이 배열에 반영
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
